#!/usr/bin/env bash
# merge_manifests.sh -- combine the per-area MANIFEST.tsv files that fetch.sh
# writes into a single human-readable sources/MANIFEST.md.
#
# Per-area manifests exist so that concurrent fetches never contend for one file;
# this rolls them up for reading. Idempotent -- safe to re-run at any time.
#
# Usage:  scripts/merge_manifests.sh
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO/sources/MANIFEST.md"

{
  echo "# Archived source documents"
  echo
  echo "Generated by \`scripts/merge_manifests.sh\` on $(date -u +%Y-%m-%d)."
  echo "Every document here was downloaded verbatim; the sha256 lets you confirm"
  echo "the bytes have not changed since retrieval."
  echo

  total=0
  for manifest in "$REPO"/sources/*/MANIFEST.tsv; do
    [ -e "$manifest" ] || continue
    area="$(basename "$(dirname "$manifest")")"
    echo "## $area"
    echo
    echo "| document | description | retrieved | bytes | sha256 | source |"
    echo "|---|---|---|---|---|---|"
    # Skip the header row, then render each record. Fields are tab-separated:
    # file, url, retrieved_utc, http, bytes, sha256, description
    dir="$(dirname "$manifest")"
    count=0
    while IFS=$'\t' read -r file url ts _http bytes sha desc; do
      [ -n "${file:-}" ] || continue
      # Skip rows whose document has since been deleted, so a probe or a
      # retracted fetch does not leave a phantom entry in the index.
      [ -e "$dir/$file" ] || continue
      printf '| `%s` | %s | %s | %s | `%s` | [link](%s) |\n' \
        "$file" "${desc:-}" "${ts%T*}" "$bytes" "${sha:0:12}" "$url"
      count=$(( count + 1 ))
    done < <(tail -n +2 "$manifest" | sort)
    echo
    total=$(( total + count ))
  done

  echo "---"
  echo
  echo "**$total documents archived.** Re-fetch any of them with:"
  echo
  echo '```'
  echo 'scripts/fetch.sh <area> <filename> <url> "<description>"'
  echo '```'
} > "$OUT"

echo "OK    wrote $(realpath --relative-to="$REPO" "$OUT")"
